POWERLEVEL9K_MODE=awesome-patched
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time context vcs dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status) # battery)
POWERLEVEL9K_TIME_FORMAT='%D{%a %b %e %H:%M:%S}'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="┌"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="└ "

source $ZSH/themes/powerlevel9k/powerlevel9k.zsh-theme
